### ISSUE TITLE
Add admin page link to /people page

### ISSUE THREAD

**Issue by FlatBallFlyer** [agile-learning-institute/mentorHub-person-ui#53]
Simple - add a link to /admin on the /people page

**Comment by WodPachua** [comment]
[PR-issue#53](https://github.com/agile-learning-institute/mentorHub-person-ui/pull/60) Here is the Pull Request for this issue.



![Image](https://github.com/agile-learning-institute/mentorHub-person-ui/assets/19221635/a997c10e-c042-430e-811b-f4f77db28cc4)
